/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_tesseract_free(a: number): void;
export function tesseract_new(): number;
export function tesseract_set_autosave(a: number): void;
export function tesseract_autosave_enabled(a: number): number;
export function tesseract_disable_key_check(a: number): void;
export function tesseract_enable_key_check(a: number): void;
export function tesseract_is_key_check_enabled(a: number): number;
export function tesseract_exist(a: number, b: number, c: number): number;
export function tesseract_clear(a: number): void;
export function tesseract_is_unlock(a: number): number;
export function tesseract_lock(a: number): void;
export function tesseract_set(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function tesseract_retrieve(a: number, b: number, c: number, d: number): void;
export function tesseract_update_unlock(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function tesseract__delete(a: number, b: number, c: number, d: number): void;
export function tesseract_unlock(a: number, b: number, c: number, d: number): void;
export function tesseract_save(a: number, b: number): void;
export function tesseract_subscribe(a: number): number;
export function tesseract_load_from_storage(a: number, b: number): void;
export function __wbg_subscription_free(a: number): void;
export function subscription_next(a: number): number;
export function __wbg_tesseracteventpromiseresult_free(a: number): void;
export function __wbg_get_tesseracteventpromiseresult_value(a: number): number;
export function __wbg_set_tesseracteventpromiseresult_value(a: number, b: number): void;
export function __wbg_get_tesseracteventpromiseresult_done(a: number): number;
export function __wbg_set_tesseracteventpromiseresult_done(a: number, b: number): void;
export function warpinstance_multipass(a: number): number;
export function __wbg_multipassbox_free(a: number): void;
export function multipassbox_create_identity(a: number, b: number, c: number, d: number, e: number): number;
export function multipassbox_get_identity(a: number, b: number, c: number): number;
export function multipassbox_get_own_identity(a: number): number;
export function multipassbox_update_identity(a: number, b: number, c: number): number;
export function __wbg_warpinstance_free(a: number): void;
export function __wbg_identityprofile_free(a: number): void;
export function identityprofile_new(a: number, b: number, c: number): number;
export function identityprofile_identity(a: number): number;
export function identityprofile_set_identity(a: number, b: number): void;
export function identityprofile_passphrase(a: number, b: number): void;
export function __wbg_identity_free(a: number): void;
export function identity_set_username(a: number, b: number, c: number): void;
export function identity_set_status_message(a: number, b: number, c: number): void;
export function identity_set_short_id(a: number, b: number, c: number): void;
export function identity_set_did_key(a: number, b: number, c: number): void;
export function identity_set_created(a: number, b: number): void;
export function identity_set_modified(a: number, b: number): void;
export function identity_username(a: number, b: number): void;
export function identity_status_message(a: number, b: number): void;
export function identity_short_id(a: number, b: number): void;
export function identity_did_key(a: number, b: number): void;
export function identity_created(a: number): number;
export function identity_modified(a: number): number;
export function generate_name(a: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha7fa496d54d0cb4c(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h2658efcc204e3bbc(a: number, b: number, c: number, d: number): void;
