export const smileys_and_emotion = [
    {
        name: "grinning face",
        glyph: "😀",
        text: ":D",
        shortname: ":grinning:",
    },
    {
        name: "grinning face with big eyes",
        glyph: "😃",
        text: ":-D",
        shortname: ":smiley:",
    },
    {
        name: "grinning face with smiling eyes",
        glyph: "😄",
        text: "=D",
        shortname: ":smile:",
    },
    {
        name: "beaming face with smiling eyes",
        glyph: "😁",
        text: ":DD",
        shortname: ":grin:",
    },
    {
        name: "grinning squinting face",
        glyph: "😆",
        text: "XD",
        shortname: ":laughing:",
    },
    {
        name: "grinning face with sweat",
        glyph: "😅",
        text: ":')",
        shortname: ":sweat_smile:",
    },
    {
        name: "rolling on the floor laughing",
        glyph: "🤣",
        text: "X'D",
        shortname: ":rofl:",
    },
    {
        name: "face with tears of joy",
        glyph: "😂",
        text: "LOL",
        shortname: ":joy:",
    },
    {
        name: "slightly smiling face",
        glyph: "🙂",
        text: ":)",
        shortname: ":slight_smile:",
    },
    {
        name: "upside-down face",
        glyph: "🙃",
        text: ":P",
        shortname: ":upside_down:",
    },
    {
        name: "melting face",
        glyph: "🫠",
        text: ":melting_face:",
        shortname: ":melting:",
    },
    {
        name: "winking face",
        glyph: "😉",
        text: ";)",
        shortname: ":wink:",
    },
    {
        name: "smiling face with smiling eyes",
        glyph: "😊",
        text: "^^",
        shortname: ":blush:",
    },
    {
        name: "smiling face with halo",
        glyph: "😇",
        text: "O:)",
        shortname: ":innocent:",
    },
    {
        name: "smiling face with hearts",
        glyph: "🥰",
        text: "<3",
        shortname: ":smiling_face_with_3_hearts:",
    },
    {
        name: "smiling face with heart-eyes",
        glyph: "😍",
        text: "<33",
        shortname: ":heart_eyes:",
    },
    {
        name: "star-struck",
        glyph: "🤩",
        text: ":*o*:",
        shortname: ":star_struck:",
    },
    {
        name: "face blowing a kiss",
        glyph: "😘",
        text: ":*",
        shortname: ":kissing_heart:",
    },
    {
        name: "kissing face",
        glyph: "😗",
        text: ":x",
        shortname: ":kissing:",
    },
    {
        name: "smiling face",
        glyph: "☺",
        text: ":]",
        shortname: ":relaxed:",
    },
    {
        name: "kissing face with closed eyes",
        glyph: "😚",
        text: ":x)",
        shortname: ":kissing_closed_eyes:",
    },
    {
        name: "kissing face with smiling eyes",
        glyph: "😙",
        text: ":*)",
        shortname: ":kissing_smiling_eyes:",
    },
    {
        name: "smiling face with tear",
        glyph: "🥲",
        text: ":')",
        shortname: ":smiling_face_with_tear:",
    },
    {
        name: "face savoring food",
        glyph: "😋",
        text: ":P~",
        shortname: ":yum:",
    },
    {
        name: "face with tongue",
        glyph: "😛",
        text: ":P",
        shortname: ":stuck_out_tongue:",
    },
    {
        name: "winking face with tongue",
        glyph: "😜",
        text: ";P",
        shortname: ":stuck_out_tongue_winking_eye:",
    },
    {
        name: "zany face",
        glyph: "🤪",
        text: "x-P",
        shortname: ":zany_face:",
    },
    {
        name: "squinting face with tongue",
        glyph: "😝",
        text: "XP",
        shortname: ":stuck_out_tongue_closed_eyes:",
    },
    {
        name: "money-mouth face",
        glyph: "🤑",
        text: ":$",
        shortname: ":money_mouth:",
    },
    {
        name: "smiling face with open hands",
        glyph: "🤗",
        text: ":hug:",
        shortname: ":hugs:",
    },
    {
        name: "face with hand over mouth",
        glyph: "🤭",
        text: ":oops:",
        shortname: ":face_with_hand_over_mouth:",
    },
    {
        name: "face with open eyes and hand over mouth",
        glyph: "🫢",
        text: ":shock:",
        shortname: ":face_with_open_eyes_and_hand_over_mouth:",
    },
    {
        name: "face with peeking eye",
        glyph: "🫣",
        text: ":peek:",
        shortname: ":face_with_peeking_eye:",
    },
    {
        name: "shushing face",
        glyph: "🤫",
        text: ":shh:",
        shortname: ":shushing_face:",
    },
    {
        name: "thinking face",
        glyph: "🤔",
        text: ":thinking:",
        shortname: ":thinking_face:",
    },
    {
        name: "saluting face",
        glyph: "🫡",
        text: ":salute:",
        shortname: ":saluting_face:",
    },
    {
        name: "zipper-mouth face",
        glyph: "🤐",
        text: ":zipit:",
        shortname: ":zipper_mouth_face:",
    },
    {
        name: "face with raised eyebrow",
        glyph: "🤨",
        text: ":/",
        shortname: ":face_with_raised_eyebrow:",
    },
    {
        name: "neutral face",
        glyph: "😐",
        text: ":|",
        shortname: ":neutral_face:",
    },
    {
        name: "expressionless face",
        glyph: "😑",
        text: "-_-",
        shortname: ":expressionless:",
    },
    {
        name: "face without mouth",
        glyph: "😶",
        text: ":X",
        shortname: ":no_mouth:",
    },
    {
        name: "dotted line face",
        glyph: "🫥",
        text: ":invisible:",
        shortname: ":dotted_line_face:",
    },
    {
        name: "face in clouds",
        glyph: "😶‍🌫️",
        text: ":fog:",
        shortname: ":face_in_clouds:",
    },
    {
        name: "smirking face",
        glyph: "😏",
        text: ":smirk:",
        shortname: ":smirking_face:",
    },
    {
        name: "unamused face",
        glyph: "😒",
        text: ":unamused:",
        shortname: ":unamused_face:",
    },
    {
        name: "face with rolling eyes",
        glyph: "🙄",
        text: ":eyeroll:",
        shortname: ":face_with_rolling_eyes:",
    },
    {
        name: "grimacing face",
        glyph: "😬",
        text: ":grimace:",
        shortname: ":grimacing_face:",
    },
    {
        name: "face exhaling",
        glyph: "😮‍💨",
        text: ":sigh:",
        shortname: ":face_exhaling:",
    },
    {
        name: "lying face",
        glyph: "🤥",
        text: ":liar:",
        shortname: ":lying_face:",
    },
    {
        name: "shaking face",
        glyph: "🫨",
        text: ":shake:",
        shortname: ":shaking_face:",
    },
    {
        name: "⊛ head shaking horizontally",
        glyph: "🙂‍↔️",
        text: ":nod_no:",
        shortname: ":head_shaking_horizontally:",
    },
    {
        name: "⊛ head shaking vertically",
        glyph: "🙂‍↕️",
        text: ":nod_yes:",
        shortname: ":head_shaking_vertically:",
    },
    {
        name: "relieved face",
        glyph: "😌",
        text: ":relief:",
        shortname: ":relieved:",
    },
    {
        name: "pensive face",
        glyph: "😔",
        text: ":(",
        shortname: ":pensive:",
    },
    {
        name: "sleepy face",
        glyph: "😪",
        text: "-_-z",
        shortname: ":sleepy:",
    },
    {
        name: "drooling face",
        glyph: "🤤",
        text: ":drool:",
        shortname: ":drooling_face:",
    },
    {
        name: "sleeping face",
        glyph: "😴",
        text: "Zzz",
        shortname: ":sleeping:",
    },
    {
        name: "face with medical mask",
        glyph: "😷",
        text: ":mask:",
        shortname: ":face_with_medical_mask:",
    },
    {
        name: "face with thermometer",
        glyph: "🤒",
        text: ":sick:",
        shortname: ":face_with_thermometer:",
    },
    {
        name: "face with head-bandage",
        glyph: "🤕",
        text: ":head_bandage:",
        shortname: ":face_with_head_bandage:",
    },
    {
        name: "nauseated face",
        glyph: "🤢",
        text: ":nauseated:",
        shortname: ":nauseated_face:",
    },
    {
        name: "face vomiting",
        glyph: "🤮",
        text: ":vomit:",
        shortname: ":face_vomiting:",
    },
    {
        name: "sneezing face",
        glyph: "🤧",
        text: ":sneeze:",
        shortname: ":sneezing_face:",
    },
    {
        name: "hot face",
        glyph: "🥵",
        text: ":hot_face:",
        shortname: ":hot_face:",
    },
    {
        name: "cold face",
        glyph: "🥶",
        text: ":cold_face:",
        shortname: ":cold_face:",
    },
    {
        name: "woozy face",
        glyph: "🥴",
        text: ":woozy:",
        shortname: ":woozy_face:",
    },
    {
        name: "face with crossed-out eyes",
        glyph: "😵",
        text: ":dizzy:",
        shortname: ":face_with_crossed_out_eyes:",
    },
    {
        name: "face with spiral eyes",
        glyph: "😵‍💫",
        text: ":spiral_eyes:",
        shortname: ":face_with_spiral_eyes:",
    },
    {
        name: "exploding head",
        glyph: "🤯",
        text: ":exploding_head:",
        shortname: ":exploding_head:",
    },
    {
        name: "cowboy hat face",
        glyph: "🤠",
        text: ":cowboy:",
        shortname: ":cowboy_hat_face:",
    },
    {
        name: "partying face",
        glyph: "🥳",
        text: ":party:",
        shortname: ":partying_face:",
    },
    {
        name: "disguised face",
        glyph: "🥸",
        text: ":disguise:",
        shortname: ":disguised_face:",
    },
    {
        name: "smiling face with sunglasses",
        glyph: "😎",
        text: "B)",
        shortname: ":sunglasses:",
    },
    {
        name: "nerd face",
        glyph: "🤓",
        text: ":nerd:",
        shortname: ":nerd_face:",
    },
    {
        name: "face with monocle",
        glyph: "🧐",
        text: ":monocle:",
        shortname: ":face_with_monocle:",
    },
    {
        name: "confused face",
        glyph: "😕",
        text: ":/",
        shortname: ":confused:",
    },
    {
        name: "face with diagonal mouth",
        glyph: "🫤",
        text: ":diag:",
        shortname: ":face_with_diagonal_mouth:",
    },
    {
        name: "worried face",
        glyph: "😟",
        text: ":-(",
        shortname: ":worried:",
    },
    {
        name: "slightly frowning face",
        glyph: "🙁",
        text: ":(",
        shortname: ":slightly_frowning_face:",
    },
    {
        name: "frowning face",
        glyph: "☹",
        text: ":frown:",
        shortname: ":frowning_face:",
    },
    {
        name: "face with open mouth",
        glyph: "😮",
        text: ":o",
        shortname: ":open_mouth:",
    },
    {
        name: "hushed face",
        glyph: "😯",
        text: ":hushed:",
        shortname: ":hushed_face:",
    },
    {
        name: "astonished face",
        glyph: "😲",
        text: ":O",
        shortname: ":astonished:",
    },
    {
        name: "flushed face",
        glyph: "😳",
        text: ":flushed:",
        shortname: ":flushed:",
    },
    {
        name: "pleading face",
        glyph: "🥺",
        text: ":plead:",
        shortname: ":pleading_face:",
    },
    {
        name: "face holding back tears",
        glyph: "🥹",
        text: ":tear:",
        shortname: ":face_holding_back_tears:",
    },
    {
        name: "frowning face with open mouth",
        glyph: "😦",
        text: ":O(",
        shortname: ":frowning_with_open_mouth:",
    },
    {
        name: "anguished face",
        glyph: "😧",
        text: "D:",
        shortname: ":anguished:",
    },
    {
        name: "fearful face",
        glyph: "😨",
        text: ":fear:",
        shortname: ":fearful:",
    },
    {
        name: "anxious face with sweat",
        glyph: "😰",
        text: ":nervous:",
        shortname: ":anxious_face_with_sweat:",
    },
    {
        name: "sad but relieved face",
        glyph: "😥",
        text: ":relieved_cry:",
        shortname: ":sad_but_relieved_face:",
    },
    {
        name: "crying face",
        glyph: "😢",
        text: ":'(",
        shortname: ":crying_face:",
    },
    {
        name: "loudly crying face",
        glyph: "😭",
        text: "T_T",
        shortname: ":loudly_crying_face:",
    },
    {
        name: "face screaming in fear",
        glyph: "😱",
        text: ":scream:",
        shortname: ":screaming_in_fear:",
    },
    {
        name: "confounded face",
        glyph: "😖",
        text: "D8",
        shortname: ":confounded:",
    },
    {
        name: "persevering face",
        glyph: "😣",
        text: ":persevere:",
        shortname: ":persevering_face:",
    },
    {
        name: "disappointed face",
        glyph: "😞",
        text: "D:",
        shortname: ":disappointed:",
    },
    {
        name: "downcast face with sweat",
        glyph: "😓",
        text: ":down_sweat:",
        shortname: ":downcast_with_sweat:",
    },
    {
        name: "weary face",
        glyph: "😩",
        text: ":weary:",
        shortname: ":weary:",
    },
    {
        name: "tired face",
        glyph: "😫",
        text: ">:(",
        shortname: ":tired_face:",
    },
    {
        name: "yawning face",
        glyph: "🥱",
        text: ":yawn:",
        shortname: ":yawning_face:",
    },
    {
        name: "face with steam from nose",
        glyph: "😤",
        text: ">:|",
        shortname: ":face_with_steam_from_nose:",
    },
    {
        name: "enraged face",
        glyph: "😡",
        text: ":angry:",
        shortname: ":rage:",
    },
    {
        name: "angry face",
        glyph: "😠",
        text: ":mad:",
        shortname: ":angry:",
    },
    {
        name: "face with symbols on mouth",
        glyph: "🤬",
        text: ":swear:",
        shortname: ":face_with_symbols_on_mouth:",
    },
    {
        name: "smiling face with horns",
        glyph: "😈",
        text: "]:)",
        shortname: ":smiling_imp:",
    },
    {
        name: "angry face with horns",
        glyph: "👿",
        text: "]:(",
        shortname: ":imp:",
    },
    {
        name: "skull",
        glyph: "💀",
        text: ":skull:",
        shortname: ":skull:",
    },
    {
        name: "skull and crossbones",
        glyph: "☠",
        text: ":pirate:",
        shortname: ":skull_and_crossbones:",
    },
    {
        name: "pile of poo",
        glyph: "💩",
        text: ":poo:",
        shortname: ":poop:",
    },
    {
        name: "clown face",
        glyph: "🤡",
        text: ":clown:",
        shortname: ":clown_face:",
    },
    {
        name: "ogre",
        glyph: "👹",
        text: ":ogre:",
        shortname: ":japanese_ogre:",
    },
    {
        name: "goblin",
        glyph: "👺",
        text: ":goblin:",
        shortname: ":japanese_goblin:",
    },
    {
        name: "ghost",
        glyph: "👻",
        text: ":ghost:",
        shortname: ":ghost:",
    },
    {
        name: "alien",
        glyph: "👽",
        text: ":alien:",
        shortname: ":alien:",
    },
    {
        name: "alien monster",
        glyph: "👾",
        text: ":monster:",
        shortname: ":space_invader:",
    },
    {
        name: "robot",
        glyph: "🤖",
        text: ":robot:",
        shortname: ":robot_face:",
    },
    {
        name: "grinning cat",
        glyph: "😺",
        text: ":cat_grin:",
        shortname: ":grinning_cat:",
    },
    {
        name: "grinning cat with smiling eyes",
        glyph: "😸",
        text: ":cat_smile:",
        shortname: ":grinning_cat_with_smiling_eyes:",
    },
    {
        name: "cat with tears of joy",
        glyph: "😹",
        text: ":cat_joy:",
        shortname: ":joy_cat:",
    },
    {
        name: "smiling cat with heart-eyes",
        glyph: "😻",
        text: ":cat_hearts:",
        shortname: ":heart_eyes_cat:",
    },
    {
        name: "cat with wry smile",
        glyph: "😼",
        text: ":cat_smirk:",
        shortname: ":smirk_cat:",
    },
    {
        name: "kissing cat",
        glyph: "😽",
        text: ":cat_kiss:",
        shortname: ":kissing_cat:",
    },
    {
        name: "weary cat",
        glyph: "🙀",
        text: ":cat_weary:",
        shortname: ":weary_cat:",
    },
    {
        name: "crying cat",
        glyph: "😿",
        text: ":cat_cry:",
        shortname: ":crying_cat_face:",
    },
    {
        name: "pouting cat",
        glyph: "😾",
        text: ":cat_pout:",
        shortname: ":pouting_cat:",
    },
    {
        name: "see-no-evil monkey",
        glyph: "🙈",
        text: ":monkey_see:",
        shortname: ":see_no_evil:",
    },
    {
        name: "hear-no-evil monkey",
        glyph: "🙉",
        text: ":monkey_hear:",
        shortname: ":hear_no_evil:",
    },
    {
        name: "speak-no-evil monkey",
        glyph: "🙊",
        text: ":monkey_speak:",
        shortname: ":speak_no_evil:",
    },
    {
        name: "love letter",
        glyph: "💌",
        text: ":love_letter:",
        shortname: ":love_letter:",
    },
    {
        name: "heart with arrow",
        glyph: "💘",
        text: "<3--",
        shortname: ":cupid:",
    },
    {
        name: "heart with ribbon",
        glyph: "💝",
        text: "<3r",
        shortname: ":gift_heart:",
    },
    {
        name: "sparkling heart",
        glyph: "💖",
        text: "<3*",
        shortname: ":sparkling_heart:",
    },
    {
        name: "growing heart",
        glyph: "💗",
        text: "<3grow",
        shortname: ":growing_heart:",
    },
    {
        name: "beating heart",
        glyph: "💓",
        text: "<3!",
        shortname: ":heartbeat:",
    },
    {
        name: "revolving hearts",
        glyph: "💞",
        text: "<3rev",
        shortname: ":revolving_hearts:",
    },
    {
        name: "two hearts",
        glyph: "💕",
        text: "<33",
        shortname: ":two_hearts:",
    },
    {
        name: "heart decoration",
        glyph: "💟",
        text: "<3decor",
        shortname: ":heart_decoration:",
    },
    {
        name: "heart exclamation",
        glyph: "❣",
        text: "<3!",
        shortname: ":heavy_heart_exclamation:",
    },
    {
        name: "broken heart",
        glyph: "💔",
        text: "</3",
        shortname: ":broken_heart:",
    },
    {
        name: "heart on fire",
        glyph: "❤️‍🔥",
        text: "<3fire",
        shortname: ":heart_on_fire:",
    },
    {
        name: "mending heart",
        glyph: "❤️‍🩹",
        text: "<3fix",
        shortname: ":mending_heart:",
    },
    {
        name: "red heart",
        glyph: "❤",
        text: "<3",
        shortname: ":heart:",
    },
    {
        name: "pink heart",
        glyph: "🩷",
        text: "<3pink",
        shortname: ":pink_heart:",
    },
    {
        name: "orange heart",
        glyph: "🧡",
        text: "<3orange",
        shortname: ":orange_heart:",
    },
    {
        name: "yellow heart",
        glyph: "💛",
        text: "<3yellow",
        shortname: ":yellow_heart:",
    },
    {
        name: "green heart",
        glyph: "💚",
        text: "<3green",
        shortname: ":green_heart:",
    },
    {
        name: "blue heart",
        glyph: "💙",
        text: "<3blue",
        shortname: ":blue_heart:",
    },
    {
        name: "light blue heart",
        glyph: "🩵",
        text: "<3lightblue",
        shortname: ":light_blue_heart:",
    },
    {
        name: "purple heart",
        glyph: "💜",
        text: "<3purple",
        shortname: ":purple_heart:",
    },
    {
        name: "brown heart",
        glyph: "🤎",
        text: "<3brown",
        shortname: ":brown_heart:",
    },
    {
        name: "black heart",
        glyph: "🖤",
        text: "<3black",
        shortname: ":black_heart:",
    },
    {
        name: "grey heart",
        glyph: "🩶",
        text: "<3grey",
        shortname: ":grey_heart:",
    },
    {
        name: "white heart",
        glyph: "🤍",
        text: "<3white",
        shortname: ":white_heart:",
    },
    {
        name: "kiss mark",
        glyph: "💋",
        text: ":kiss:",
        shortname: ":kiss_mark:",
    },
    {
        name: "hundred points",
        glyph: "💯",
        text: ":100:",
        shortname: ":100:",
    },
    {
        name: "anger symbol",
        glyph: "💢",
        text: ":anger:",
        shortname: ":anger:",
    },
    {
        name: "collision",
        glyph: "💥",
        text: ":collision:",
        shortname: ":collision:",
    },
    {
        name: "dizzy",
        glyph: "💫",
        text: ":dizzy:",
        shortname: ":dizzy:",
    },
    {
        name: "sweat droplets",
        glyph: "💦",
        text: ":sweat:",
        shortname: ":sweat_droplets:",
    },
    {
        name: "dashing away",
        glyph: "💨",
        text: ":dash:",
        shortname: ":dashing_away:",
    },
    {
        name: "hole",
        glyph: "🕳",
        text: ":hole:",
        shortname: ":hole:",
    },
    {
        name: "speech balloon",
        glyph: "💬",
        text: ":speech:",
        shortname: ":speech_balloon:",
    },
    {
        name: "eye in speech bubble",
        glyph: "👁️‍🗨️",
        text: ":eye_speech:",
        shortname: ":eye_in_speech_bubble:",
    },
    {
        name: "left speech bubble",
        glyph: "🗨",
        text: ":left_speech:",
        shortname: ":left_speech_bubble:",
    },
    {
        name: "right anger bubble",
        glyph: "🗯",
        text: ":anger_bubble:",
        shortname: ":right_anger_bubble:",
    },
    {
        name: "thought balloon",
        glyph: "💭",
        text: ":thought:",
        shortname: ":thought_balloon:",
    },
    {
        name: "ZZZ",
        glyph: "💤",
        text: "zzz",
        shortname: ":zzz:",
    },
]
