export const MAX_THUMBNAIL_SIZE: number = 5_242_880
export const MAX_IMAGE_SIZE: number = 2_097_152
export const MIN_USERNAME_LENGTH: number = 4
export const MAX_USERNAME_LENGTH: number = 64
export const MAX_STATUS_MESSAGE_LENGTH: number = 128
export const MIN_MESSAGE_SIZE: number = 1
export const MAX_MESSAGE_SIZE: number = 4_096
export const MAX_ATTACHMENT: number = 32
export const MIN_ATTACHMENT: number = 1
export const MAX_CONVERSATIONS: number = 1_000
export const MAX_FRIENDS: number = 1_000
export const MAX_REQUEST: number = 1_000
export const MIN_PIN_LENGTH = 4
export const MAX_PIN_LENGTH = 8
